rabbitmq:
  image: rabbitmq:3.6.5-management
  restart: on-failure:5
  ports:
    - 5672:5672
redis:
  image: redis:3.2.3
  restart: on-failure:5
  ports:
    - 6379:6379
api:
  build: .
  links:
    - redis
    - rabbitmq
  environment:
    TRANSPORT_NAME: rabbitmq
    REDIS_HOST: redis
    RABBITMQ_HOST: rabbitmq
  command: api
  ports:
    - 4567:4567
server:
  build : .
  links:
    - redis
    - api
    - rabbitmq
  environment:
    REDIS_HOST: redis
    API_HOST: sensu_api
    TRANSPORT_NAME: rabbitmq
    RABBITMQ_HOST: rabbitmq
  command: server
client:
  build: .
  links:
    - redis
    - api
    - rabbitmq
  environment:
    REDIS_HOST: redis
    API_HOST: sensu_api
    TRANSPORT_NAME: rabbitmq
    CLIENT_NAME: test
    CLIENT_SUBSCRIPTIONS: all
    CLIENT_ADDRESS: 127.0.0.1
    # RUNTIME_INSTALL: postgres
    RABBITMQ_HOST: rabbitmq
  command: client
uchiwa:
  build: docker-uchiwa
  links:
    - api
  ports:
    - '80:3000'
